language: node_js
node_js: "10"
jobs:
  include:
    - stage: test
      name: "copr build test"
      script:
        - export SPEC=iml-realtime.spec
        - docker run -it -e SPEC="$SPEC" -e LOCAL_ONLY="True" -v $(pwd):/build:rw imlteam/copr
        - ((`find _topdir/RPMS -name *.rpm | wc -l` > 0))
    - stage: test
      name: "Lint & Test"
      script:
        - npm run eslint
        - npm run test
    - stage: deploy-npm
      name: "npm Deploy"
      script: skip
      deploy:
        provider: npm
        email: "$NPM_EMAIL"
        api_key: "$NPM_TOKEN"
        on:
          all_branches: true
    - stage: cd
      name: "Continuous Deployment"
      script:
        - export OWNER=managerforlustre
        - export PROJECT=manager-for-lustre-devel
        - export PACKAGE=iml-realtime
        - export SPEC=iml-realtime.spec
        - docker run -it -e OWNER="$OWNER" -e PROJECT="$PROJECT" -e PACKAGE="$PACKAGE" -e SPEC="$SPEC" -e KEY="$encrypted_253525cedcf6_key" -e IV="$encrypted_253525cedcf6_iv" -v $(pwd):/build:rw imlteam/copr
    - stage: deploy-copr-r5.0
      name: "Copr deploy"
      script:
        - export OWNER=managerforlustre
        - export PROJECT=manager-for-lustre-5.0
        - export PACKAGE=iml-realtime
        - export SPEC=iml-realtime.spec
        - docker run -it -e OWNER="$OWNER" -e PROJECT="$PROJECT" -e PACKAGE="$PACKAGE" -e SPEC="$SPEC" -e KEY="$encrypted_253525cedcf6_key" -e IV="$encrypted_253525cedcf6_iv" -v $(pwd):/build:rw imlteam/copr
stages:
  - test
  - name: deploy-npm
    if: branch =~ ^v\d+\.\d+\.\d+-1.*$
  - name: deploy-copr-r5.0
    if: branch =~ ^v\d+\.\d+\.\d+-.+-r5\.0$
  - name: cd
    if: branch = master AND type = push AND fork = false
